// Builds the launch posts from posts.html.
//
//   node build.js            renders/  finished posts (JPG)  + plates/ (photo only, no type)
//   node build.js <base-url> also writes canva-feed.html and canva-story.html:
//                            each page is its plate plus the copy as live text at
//                            the exact measured position, so Canva's HTML import
//                            gives an editable design that matches the render.
//
// Needs Playwright (Node). Plates in the Canva files are loaded from <base-url>,
// which must be a public URL for this folder that serves images.
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');

const PAGES = { 'post-1': 'feed', 'post-2': 'feed', 'post-3': 'feed', 'story-1': 'story' };
const COPY = '.eyebrow, .h1, .line, .name, .price, .big, .pill, .link';

(async () => {
  const base = process.argv[2];
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1200, height: 2000 } });
  await page.goto('file://' + path.join(__dirname, 'posts.html'));
  await page.evaluate(() => document.fonts.ready);
  await page.waitForLoadState('networkidle');

  for (const dir of ['renders', 'plates']) fs.mkdirSync(path.join(__dirname, dir), { recursive: true });
  for (const id of Object.keys(PAGES)) {
    await page.locator('#' + id).screenshot({ path: path.join(__dirname, 'renders', `zorev-launch-${id}.jpg`), type: 'jpeg', quality: 95 });
  }

  // Measure the copy before hiding it.
  const layout = await page.evaluate(({ ids, sel }) => ids.map(id => {
    const p = document.getElementById(id), o = p.getBoundingClientRect();
    const items = [...p.querySelectorAll(sel)].map(el => {
      const r = el.getBoundingClientRect(), cs = getComputedStyle(el);
      return {
        cls: el.classList[0], text: el.textContent.replace(/ /g, ' '),
        x: r.left - o.left, y: r.top - o.top, w: r.width, h: r.height,
        font: cs.fontFamily.split(',')[0].replace(/"/g, ''), size: cs.fontSize, weight: cs.fontWeight,
        color: cs.color, tracking: cs.letterSpacing, lh: cs.lineHeight, upper: cs.textTransform === 'uppercase',
        bg: cs.backgroundColor, radius: cs.borderRadius,
      };
    });
    return { id, label: p.dataset.label, w: o.width, h: o.height, items };
  }), { ids: Object.keys(PAGES), sel: COPY });

  await page.evaluate(() => document.body.classList.add('bg-only'));
  for (const id of Object.keys(PAGES)) {
    await page.locator('#' + id).screenshot({ path: path.join(__dirname, 'plates', `zorev-launch-${id}-plate.jpg`), type: 'jpeg', quality: 92 });
  }
  await browser.close();
  console.log('renders/ and plates/ written');
  if (!base) return;

  const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const textCss = i => `font-family:'${i.font}';font-size:${i.size};font-weight:${i.weight};color:${i.color};` +
    `letter-spacing:${i.tracking};line-height:${i.lh};margin:0;white-space:${i.cls === 'h1' ? 'normal' : 'nowrap'}`;
  const pageHtml = p => {
    const els = p.items.map(i => {
      const text = esc(i.upper ? i.text.toUpperCase() : i.text);
      const box = `position:absolute;left:${i.x.toFixed(1)}px;top:${i.y.toFixed(1)}px;width:${(i.w + (i.cls === 'h1' ? 0 : 6)).toFixed(1)}px`;
      if (i.cls === 'pill') {
        return `    <div style="${box};height:${i.h}px;background:${i.bg};border-radius:${i.h / 2}px;display:flex;align-items:center;justify-content:center">` +
               `<p style="${textCss(i)}">${text}</p></div>`;
      }
      const align = p.id === 'post-2' ? ';text-align:center' : '';
      return `    <p style="${box};${textCss(i)}${align}">${text}</p>`;
    });
    return `  <section data-document-role="page" data-label="${esc(p.label)}" style="position:relative;width:${p.w}px;height:${p.h}px;overflow:hidden">\n` +
      `    <img src="${base}/plates/zorev-launch-${p.id}-plate.jpg" alt="" style="position:absolute;left:0;top:0;width:${p.w}px;height:${p.h}px">\n` +
      els.join('\n') + `\n  </section>`;
  };
  for (const set of ['feed', 'story']) {
    const pages = layout.filter(p => PAGES[p.id] === set);
    const html = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>ZOREV launch, ${set}</title>\n` +
      `<link href="https://fonts.googleapis.com/css2?family=Newsreader&family=Public+Sans:wght@400;500;600&display=swap" rel="stylesheet">\n` +
      `<style>body{margin:0}</style>\n</head>\n<body>\n` +
      `<!-- Generated by build.js from posts.html. For Canva's HTML import; edit posts.html instead. -->\n` +
      pages.map(pageHtml).join('\n') + `\n</body>\n</html>\n`;
    fs.writeFileSync(path.join(__dirname, `canva-${set}.html`), html);
    console.log(`canva-${set}.html written (${pages.length} page${pages.length > 1 ? 's' : ''})`);
  }
})();
